import React, { createContext, useContext, useState } from 'react';

/* ─── helpers ─── */
export const fmtEur = (n) =>
  Number(n).toLocaleString('bg-BG', { minimumFractionDigits: 0, maximumFractionDigits: 0 }) + ' €';

const translations = {
  bg: {
    appTitle: 'Апартамент Мениджър',
    /* Tabs */
    tabs: { calendar: 'Календар', bookings: 'Резервации', new: 'Нова', revenue: 'Приходи', expenses: 'Разходи' },
    /* Filters */
    filters: { all: 'Всички', paid: 'Платени', pending: 'Очакват', partial: 'Частични', cancelled: 'Отменени' },
    /* Status */
    status:     { paid: 'Платено',  pending: 'Очаква',         partial: 'Частично',         cancelled: 'Отменена' },
    statusLong: { paid: 'Платено',  pending: 'Очаква плащане', partial: 'Частично платено', cancelled: 'Отменена' },
    /* Sources */
    sources: { 'Директна': 'Директна', 'Airbnb': 'Airbnb', 'Booking.com': 'Booking.com', 'OLX': 'OLX', 'Facebook': 'Facebook', 'Друго': 'Друго' },
    /* Dates */
    months: ['Януари','Февруари','Март','Април','Май','Юни','Юли','Август','Септември','Октомври','Ноември','Декември'],
    dow: ['Пн','Вт','Ср','Чт','Пт','Сб','Нд'],
    /* BookingList */
    searchPlaceholder: 'Търси по име...',
    filterDatePh:  'Филтър по период',
    filterActive:  (n) => `${n} рез. в периода`,
    noBookings:    'Няма намерени резервации',
    colGuest:      'Гост',
    colPlatform:   'Платформа',
    colAmount:     'Сума',
    colStatus:     'Статус',
    colActions:    'Действия',
    nights:        (n) => `${n} нощ.`,
    persons:       (n) => `${n} лица`,
    activeLabel:   'Настанен',
    todayLabel:    'Днес',
    inDays:        (n) => `след ${n} дни`,
    /* BookingForm */
    newBookingTitle:   'Нова резервация',
    secGuest:          'Гост',
    secStay:           'Период на престой',
    secPayment:        'Плащане и източник',
    secNotes:          'Бележки',
    fldName:           'Имена *',
    fldPersons:        'Брой лица',
    fldPhone:          'Телефон',
    fldEmail:          'Имейл',
    fldAmount:         'Обща сума (€) *',
    fldStatus:         'Статус',
    fldPlatform:       'Платформа',
    fldApartment:      'Имот',
    phName:            'Иван Петров',
    phPhone:           '0888 123 456',
    phNotes:           'Допълнителна информация...',
    phAmount:          '0',
    optPending:        'Очаква плащане',
    optPartial:        'Частично платено',
    optPaid:           'Платено',
    fldPaidAmount:     'Платено досега (€)',
    lblPaidAmount:     'Платено',
    lblRemaining:      'Оставащо',
    errPaidAmount:     'Сумата трябва да е между 0 и общата сума',
    errSave:           'Грешка при запазване. Опитай отново.',
    optDirect:         'Директна',
    optOther:          'Друго',
    fldNightRate:      'Цена на нощ (€)',
    phNightRate:       '0',
    calcNights:        (n, r, t) => `${n} нощи × ${r} € = ${t} €`,
    btnSave:           'Запази',
    errRequired:       'Полето е задължително',
    errCheckout:       'Датата на напускане трябва да е след настаняването',
    errAmount:         'Въведете валидна сума',
    conflictMsg:       (n, ci, co) => `Датите се припокриват с резервацията на ${n} (${ci} – ${co}).`,
    /* BookingModal */
    lblPhone:    'Телефон',   lblEmail:    'Имейл',
    lblCheckin:  'Настаняване', lblCheckout: 'Напускане',
    lblNights:   'Нощувки',   lblPersons:  'Лица',
    lblAmount:   'Сума',      lblSource:   'Източник',
    lblNotes:    'Бележки',
    editTitle:   'Редактирай резервация',
    btnEdit:     'Редактирай',
    btnMarkPaid: 'Маркирай като платено',
    btnCancelBkg:'Отмени резервацията',
    btnDelete:   'Изтрий',
    btnClose:    'Затвори',
    confirmDel:       (n) => `Изтрий резервацията на ${n}?`,
    confirmPaidMsg:   'Маркирай тази резервация като платена?',
    confirmCancelMsg: 'Отмени тази резервация?',
    confirmDelShort:  'Изтрий?',
    confirmCancelShort: 'Отмени?',
    confirmPaidShort: 'Платено?',
    btnConfirm:       'Потвърди',
    /* Revenue */
    statTotal:       'Общо приходи',
    statActive:      (n) => `${n} активни резервации`,
    statPaid:        'Платено',
    statPaidCount:   (n) => `${n} резервации`,
    statPending:     'Очаква плащане',
    statExpenses:    'Разходи',
    statNet:         'Нетна печалба',
    statNights:      (y) => `Наети нощи за ${y} г.`,
    statNightsFrom:  'от всички активни резервации',
    statNightsUnit:  'нощи',
    collected:       'Събрани средства',
    pctPaid:         (n) => `${Math.round(n)}% платено`,
    byPlatform:      'По платформа',
    ofTotal:         'от общото',
    allYears:        'Всички години',
    byMonth:         'По месеци',
    noRevData:       'Няма данни за приходи',
    colMonth:        'Месец',
    colRes:          'Рез.',
    colRevenue:      'Приходи',
    /* Calendar */
    calNoBookings:   'Няма резервации',
    calStats:        (n, pct) => `${n} рез. · ${pct}% заетост`,
    calLegDirect:    'Директна',
    calLegOther:     'Друго',
    /* Auth */
    authWelcome:        'Добре дошли',
    authSubtitle:       'Влез в своя акаунт',
    authSubtitleReg:    'Създай акаунт',
    authFirstName:      'Име',
    authLastName:       'Фамилия',
    authEmail:          'Имейл',
    authPassword:       'Парола',
    authConfirmPass:    'Потвърди паролата',
    authLogin:          'Вход',
    authRegister:       'Регистрация',
    authSubmitLogin:    'Влез',
    authSubmitReg:      'Създай акаунт',
    authToRegister:     'Нямаш акаунт?',
    authToLogin:        'Вече имаш акаунт?',
    authLogout:         'Изход',
    authErrInvalid:     'Грешен имейл или парола.',
    authErrEmail:       'Въведи валиден имейл.',
    authErrPassword:    'Паролата трябва да е поне 6 символа.',
    authErrExists:      'Акаунт с този имейл вече съществува.',
    authErrConfirmPass: 'Паролите не съвпадат.',
    authErrName:        'Въведи ime и фамилия.',
    authSuccessReg:     'Акаунтът е създаден! Можеш да влезеш.',
    authCheckEmail:     'Провери имейла си',
    authCheckEmailMsg:  (email) => `Изпратихме потвърждение на ${email}. Натисни линка в имейла за да активираш акаунта.`,
    authCheckEmailBack: '← Назад към вход',
    authForgotPassword:     'Забравена парола?',
    authForgotTitle:        'Нулиране на парола',
    authForgotSubtitle:     'Въведи имейла си и ще ти изпратим линк за нулиране',
    authForgotBtn:          'Изпрати линк',
    authForgotSentTitle:    'Провери имейла си',
    authForgotSentMsg:      (email) => `Изпратихме линк за нулиране на ${email}.`,
    authForgotBack:         '← Назад към вход',
    authNewPassword:        'Нова парола',
    authConfirmNewPassword: 'Потвърди новата парола',
    authResetBtn:           'Запази новата парола',
    authResetSuccess:       'Паролата е сменена успешно!',
    /* Onboarding */
    onboardTitle:    'Добре дошли!',
    onboardSubtitle: 'Добавете първия си имот за да започнете',
    onboardName:     'Име на имота *',
    onboardAddress:  'Адрес (незадължително)',
    onboardBtn:      'Добави имот',
    onboardContinue: 'Продължи',
    onboardAddMore:  'Добави друг имот',
    onboardAdded:    'Добавени имоти',
    /* Apartments */
    aptAll:      'Всички имоти',
    aptManage:   'Управление на имоти',
    aptTitle:    'Имоти',
    aptAdd:      'Добави имот',
    aptEdit:     'Редактирай имот',
    aptNoApts:   'Нямате добавени имоти',
    aptNamePh:   'Апартамент 1',
    aptAddressPh:'гр. София, бул. Витоша 1',
    aptNotesPh:  'Допълнителна информация...',
    aptNone:     'Без имот',
    /* Expenses */
    expAdd:         'Нов разход',
    expEdit:        'Редактирай разход',
    expNoExp:       'Няма добавени разходи',
    expDate:        'Дата',
    expAmount:      'Сума (€)',
    expCategory:    'Категория',
    expDescription: 'Описание',
    expDescPh:      'Бележка за разхода...',
    expTotal:       'Общо разходи',
    expEntries:     'записа',
    expCats: {
      'Почистване': 'Почистване',
      'Ремонт':     'Ремонт',
      'Поддръжка':  'Поддръжка',
      'Комунални':  'Комунални',
      'Данъци':     'Данъци',
      'Друго':      'Друго',
    },
    /* DateRangePicker */
    drpPlaceholder:  'Изберете период на престой',
    drpPickEnd:      'изберете напускане',
    drpHintStart:    'Изберете дата на настаняване',
    drpHintEnd:      'Изберете дата на напускане',
    drpNights:       (n) => `${n} ${n === 1 ? 'нощувка' : 'нощувки'}`,
    drpBooked:       'Заето',
    drpTurnover:     'Смяна',
    drpSelected:     'Избрано',
  },

  en: {
    appTitle: 'Apartment Manager',
    tabs: { calendar: 'Calendar', bookings: 'Bookings', new: 'New', revenue: 'Revenue', expenses: 'Expenses' },
    filters: { all: 'All', paid: 'Paid', pending: 'Pending', partial: 'Partial', cancelled: 'Cancelled' },
    status:     { paid: 'Paid',  pending: 'Pending',          partial: 'Partial',          cancelled: 'Cancelled' },
    statusLong: { paid: 'Paid',  pending: 'Awaiting payment', partial: 'Partially paid',   cancelled: 'Cancelled' },
    sources: { 'Директна': 'Direct', 'Airbnb': 'Airbnb', 'Booking.com': 'Booking.com', 'OLX': 'OLX', 'Facebook': 'Facebook', 'Друго': 'Other' },
    months: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    dow: ['Mo','Tu','We','Th','Fr','Sa','Su'],
    searchPlaceholder: 'Search by name...',
    filterDatePh:  'Filter by period',
    filterActive:  (n) => `${n} bkg${n === 1 ? '' : 's'} in period`,
    noBookings:    'No bookings found',
    colGuest:      'Guest',
    colPlatform:   'Platform',
    colAmount:     'Amount',
    colStatus:     'Status',
    colActions:    'Actions',
    nights:        (n) => `${n} nights`,
    persons:       (n) => `${n} guests`,
    activeLabel:   'Checked in',
    todayLabel:    'Today',
    inDays:        (n) => n === 1 ? 'Tomorrow' : `in ${n} days`,
    newBookingTitle:   'New Booking',
    secGuest:          'Guest',
    secStay:           'Stay Period',
    secPayment:        'Payment & Source',
    secNotes:          'Notes',
    fldName:           'Full Name *',
    fldPersons:        'Guests',
    fldPhone:          'Phone',
    fldEmail:          'Email',
    fldAmount:         'Total Amount (€) *',
    fldStatus:         'Status',
    fldPlatform:       'Platform',
    fldApartment:      'Property',
    phName:            'John Smith',
    phPhone:           '+359 888 123 456',
    phNotes:           'Additional information...',
    phAmount:          '0',
    optPending:        'Awaiting payment',
    optPartial:        'Partially paid',
    optPaid:           'Paid',
    fldPaidAmount:     'Paid so far (€)',
    lblPaidAmount:     'Paid',
    lblRemaining:      'Remaining',
    errPaidAmount:     'Amount must be between 0 and the total',
    errSave:           'Save failed. Please try again.',
    optDirect:         'Direct',
    optOther:          'Other',
    fldNightRate:      'Night rate (€)',
    phNightRate:       '0',
    calcNights:        (n, r, t) => `${n} nights × ${r} € = ${t} €`,
    btnSave:           'Save',
    errRequired:       'This field is required',
    errCheckout:       'Check-out must be after check-in',
    errAmount:         'Enter a valid amount',
    conflictMsg:       (n, ci, co) => `Dates overlap with ${n}'s booking (${ci} – ${co}).`,
    lblPhone:    'Phone',     lblEmail:    'Email',
    lblCheckin:  'Check-in',  lblCheckout: 'Check-out',
    lblNights:   'Nights',    lblPersons:  'Guests',
    lblAmount:   'Amount',    lblSource:   'Source',
    lblNotes:    'Notes',
    editTitle:   'Edit Booking',
    btnEdit:     'Edit',
    btnMarkPaid: 'Mark as paid',
    btnCancelBkg:'Cancel booking',
    btnDelete:   'Delete',
    btnClose:    'Close',
    confirmDel:       (n) => `Delete ${n}'s booking?`,
    confirmPaidMsg:   'Mark this booking as paid?',
    confirmCancelMsg: 'Cancel this booking?',
    confirmDelShort:  'Delete?',
    confirmCancelShort: 'Cancel?',
    confirmPaidShort: 'Mark paid?',
    btnConfirm:       'Confirm',
    statTotal:       'Total Revenue',
    statActive:      (n) => `${n} active bookings`,
    statPaid:        'Paid',
    statPaidCount:   (n) => `${n} bookings`,
    statPending:     'Awaiting Payment',
    statExpenses:    'Expenses',
    statNet:         'Net Profit',
    statNights:      (y) => `Nights booked in ${y}`,
    statNightsFrom:  'from all active bookings',
    statNightsUnit:  'nights',
    collected:       'Collected funds',
    pctPaid:         (n) => `${Math.round(n)}% paid`,
    byPlatform:      'By Platform',
    ofTotal:         'of total',
    allYears:        'All years',
    byMonth:         'By Month',
    noRevData:       'No revenue data',
    colMonth:        'Month',
    colRes:          'Bkgs.',
    colRevenue:      'Revenue',
    calNoBookings:   'No bookings',
    calStats:        (n, pct) => `${n} bkgs · ${pct}% occupancy`,
    calLegDirect:    'Direct',
    calLegOther:     'Other',
    /* Auth */
    authWelcome:        'Welcome',
    authSubtitle:       'Sign in to your account',
    authSubtitleReg:    'Create an account',
    authFirstName:      'First name',
    authLastName:       'Last name',
    authEmail:          'Email',
    authPassword:       'Password',
    authConfirmPass:    'Confirm password',
    authLogin:          'Login',
    authRegister:       'Register',
    authSubmitLogin:    'Sign in',
    authSubmitReg:      'Create account',
    authToRegister:     "Don't have an account?",
    authToLogin:        'Already have an account?',
    authLogout:         'Log out',
    authErrInvalid:     'Invalid email or password.',
    authErrEmail:       'Please enter a valid email.',
    authErrPassword:    'Password must be at least 6 characters.',
    authErrExists:      'An account with this email already exists.',
    authErrConfirmPass: 'Passwords do not match.',
    authErrName:        'Please enter your first and last name.',
    authSuccessReg:     'Account created! You can now sign in.',
    authCheckEmail:     'Check your email',
    authCheckEmailMsg:  (email) => `We sent a confirmation link to ${email}. Click it to activate your account.`,
    authCheckEmailBack: '← Back to sign in',
    authForgotPassword:     'Forgot password?',
    authForgotTitle:        'Reset password',
    authForgotSubtitle:     'Enter your email and we\'ll send you a reset link',
    authForgotBtn:          'Send reset link',
    authForgotSentTitle:    'Check your email',
    authForgotSentMsg:      (email) => `We sent a reset link to ${email}.`,
    authForgotBack:         '← Back to sign in',
    authNewPassword:        'New password',
    authConfirmNewPassword: 'Confirm new password',
    authResetBtn:           'Save new password',
    authResetSuccess:       'Password changed successfully!',
    /* Onboarding */
    onboardTitle:    'Welcome!',
    onboardSubtitle: 'Add your first property to get started',
    onboardName:     'Property name *',
    onboardAddress:  'Address (optional)',
    onboardBtn:      'Add property',
    onboardContinue: 'Continue',
    onboardAddMore:  'Add another property',
    onboardAdded:    'Added properties',
    /* Apartments */
    aptAll:      'All properties',
    aptManage:   'Manage properties',
    aptTitle:    'Properties',
    aptAdd:      'Add property',
    aptEdit:     'Edit property',
    aptNoApts:   'No properties added yet',
    aptNamePh:   'Apartment 1',
    aptAddressPh:'123 Main St, City',
    aptNotesPh:  'Additional information...',
    aptNone:     'No property',
    /* Expenses */
    expAdd:         'Add expense',
    expEdit:        'Edit expense',
    expNoExp:       'No expenses added',
    expDate:        'Date',
    expAmount:      'Amount (€)',
    expCategory:    'Category',
    expDescription: 'Description',
    expDescPh:      'Note about this expense...',
    expTotal:       'Total expenses',
    expEntries:     'entries',
    expCats: {
      'Почистване': 'Cleaning',
      'Ремонт':     'Repair',
      'Поддръжка':  'Maintenance',
      'Комунални':  'Utilities',
      'Данъци':     'Taxes',
      'Друго':      'Other',
    },
    /* DateRangePicker */
    drpPlaceholder:  'Select stay period',
    drpPickEnd:      'select check-out',
    drpHintStart:    'Select check-in date',
    drpHintEnd:      'Select check-out date',
    drpNights:       (n) => `${n} ${n === 1 ? 'night' : 'nights'}`,
    drpBooked:       'Booked',
    drpTurnover:     'Turnover',
    drpSelected:     'Selected',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    // Migration: if the user never explicitly picked a language (old default was 'bg'),
    // reset to 'en'. We track explicit picks with 'lang-set'.
    if (!localStorage.getItem('lang-set')) {
      localStorage.removeItem('lang');
      return 'en';
    }
    return localStorage.getItem('lang') || 'en';
  });

  function toggleLang() {
    const next = lang === 'bg' ? 'en' : 'bg';
    localStorage.setItem('lang', next);
    localStorage.setItem('lang-set', '1');
    setLang(next);
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
